

######### Cadastro Tópico 
POST http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.TM4EY0zxfclSkjfPwMKWDkhaWtF6lnBWggCZE7fKpGE3X9xgdvNh0VRk7tfn

{
    "name": "Web1"

}

######### Listar todos os Tópico 
GET http://127.0.0.1:3333/topics HTTP/1.1 
Content-Type: application/json
Authorization: Bearer Mg.TM4EY0zxfclSkjfPwMKWDkhaWtF6lnBWggCZE7fKpGE3X9xgdvNh0VRk7tfn

######### Listar Tópico específico
GET http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json
Authorization: Bearer Mg.TM4EY0zxfclSkjfPwMKWDkhaWtF6lnBWggCZE7fKpGE3X9xgdvNh0VRk7tfn

######### Alterar Tópico 
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer Mg.TM4EY0zxfclSkjfPwMKWDkhaWtF6lnBWggCZE7fKpGE3X9xgdvNh0VRk7tfn

{
    "name": "Web II"

}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json
Authorization: Bearer Mg.TM4EY0zxfclSkjfPwMKWDkhaWtF6lnBWggCZE7fKpGE3X9xgdvNh0VRk7tfn
